export const PERMISSIONS = {
  LOGIN: 'LOGIN', TICKET_CREATE: 'TICKET_CREATE', TICKET_VIEW_OWN: 'TICKET_VIEW_OWN', TICKET_VIEW_ALL: 'TICKET_VIEW_ALL',
  TICKET_EDIT_OWN: 'TICKET_EDIT_OWN', TICKET_STATUS_CHANGE: 'TICKET_STATUS_CHANGE', TICKET_ASSIGN: 'TICKET_ASSIGN',
  TICKET_REASSIGN: 'TICKET_REASSIGN', TICKET_ESCALATE: 'TICKET_ESCALATE', COMMENT_PUBLIC: 'COMMENT_PUBLIC',
  COMMENT_INTERNAL: 'COMMENT_INTERNAL', ATTACHMENT_UPLOAD: 'ATTACHMENT_UPLOAD', CATEGORY_MANAGE: 'CATEGORY_MANAGE',
  PRIORITY_MANAGE: 'PRIORITY_MANAGE', SLA_MANAGE: 'SLA_MANAGE', USER_MANAGE: 'USER_MANAGE', DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  DASHBOARD_VIEW_LIMITED: 'DASHBOARD_VIEW_LIMITED', REPORT_VIEW: 'REPORT_VIEW', REPORT_VIEW_LIMITED: 'REPORT_VIEW_LIMITED',
  SURVEY_RESPOND: 'SURVEY_RESPOND', KNOWLEDGE_MANAGE: 'KNOWLEDGE_MANAGE',
} as const

export const ROLE_PERMISSION_CODES = {
  ADMIN: Object.values(PERMISSIONS),
  SUPERVISOR: [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_VIEW_ALL, PERMISSIONS.TICKET_EDIT_OWN, PERMISSIONS.TICKET_STATUS_CHANGE, PERMISSIONS.TICKET_ASSIGN, PERMISSIONS.TICKET_REASSIGN, PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.SLA_MANAGE, PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.REPORT_VIEW, PERMISSIONS.KNOWLEDGE_MANAGE],
  AGENT: [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_STATUS_CHANGE, PERMISSIONS.TICKET_ESCALATE, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.COMMENT_INTERNAL, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.DASHBOARD_VIEW_LIMITED, PERMISSIONS.REPORT_VIEW_LIMITED, PERMISSIONS.KNOWLEDGE_MANAGE],
  REQUESTER: [PERMISSIONS.LOGIN, PERMISSIONS.TICKET_CREATE, PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_EDIT_OWN, PERMISSIONS.COMMENT_PUBLIC, PERMISSIONS.ATTACHMENT_UPLOAD, PERMISSIONS.SURVEY_RESPOND],
} as const
