import type { UserRole } from '@/types/user.types'
import { PERMISSIONS } from '@/types/permission.types'

export const ROLES: Record<UserRole, string> = {
  ADMIN: 'Administrador',
  SUPERVISOR: 'Supervisor',
  AGENT: 'Agente',
  REQUESTER: 'Solicitante',
}

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  SUPERVISOR: [
    PERMISSIONS.LOGIN,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_OWN,
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_EDIT_OWN,
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_REASSIGN,
    PERMISSIONS.TICKET_ESCALATE,
    PERMISSIONS.COMMENT_PUBLIC,
    PERMISSIONS.COMMENT_INTERNAL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.SLA_MANAGE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.KNOWLEDGE_MANAGE,
  ],
  AGENT: [
    PERMISSIONS.LOGIN,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_OWN,
    PERMISSIONS.TICKET_STATUS_CHANGE,
    PERMISSIONS.TICKET_ESCALATE,
    PERMISSIONS.COMMENT_PUBLIC,
    PERMISSIONS.COMMENT_INTERNAL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.DASHBOARD_VIEW_LIMITED,
    PERMISSIONS.REPORT_VIEW_LIMITED,
    PERMISSIONS.KNOWLEDGE_MANAGE,
  ],
  REQUESTER: [
    PERMISSIONS.LOGIN,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_OWN,
    PERMISSIONS.TICKET_EDIT_OWN,
    PERMISSIONS.COMMENT_PUBLIC,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.SURVEY_RESPOND,
  ],
}

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  '/dashboard': [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.DASHBOARD_VIEW_LIMITED],
  '/tickets': [PERMISSIONS.TICKET_VIEW_OWN, PERMISSIONS.TICKET_VIEW_ALL],
  '/tickets/create': [PERMISSIONS.TICKET_CREATE],
  '/catalogs': [PERMISSIONS.CATEGORY_MANAGE, PERMISSIONS.PRIORITY_MANAGE, PERMISSIONS.SLA_MANAGE],
  '/users': [PERMISSIONS.USER_MANAGE],
  '/reports': [PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_VIEW_LIMITED],
}
